config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  get 'comments/destroy'
  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'posts#index'
  post '/', to: 'posts#create'

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  resources :likes, only: [:index, :create, :destroy]
  resources :users, only: :show 
  resources :rankings, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  def self.ranking
    self.group(:post_id).order('count_post_id DESC').count(:post_id)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :name, presence: true, length: {maximum: 50}
  validates :area, presence: true, length: {maximum: 50}
  validates :shop, presence: true, length: {maximum: 50}
  validates :broth, presence: true, length: {maximum: 50}
  validates :price, presence: true
  validates :image, presence: true
 
  belongs_to :user
  has_many :likes
  has_many :comments

  has_one_attached :image

  def self.csv_attributes
    ["shop", "name", "price", "broth", "area", "content", "created_at"]
  end

  def self.generate_csv
    CSV.generate(headers: true) do |csv|
      csv << csv_attributes
      all.each do |post|
        csv << csv_attributes.map{|attr| post.send(attr)}
      end
    end
  end

  def thumbnail
    return self.image.variant(combine_options: {resize: '550', gravity: 'Center', crop: '550x550+0+0'})
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :has_liked, through: :likes, source: :post
  has_many :comments, dependent: :destroy
  
  def like(post)
    self.likes.find_or_create_by(post_id: post.id)
  end

  def unlike(post)
    like = self.likes.find_by(post_id: post.id)
    like.destroy if like
  end

  def has_liked?(post)
    self.has_liked.include?(post)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private

  def counter(post)
    @count_likes = post.likes.count
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post

  def create
   
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      redirect_to @post
    else
      redirect_to @post
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy if @comment
    redirect_to @post
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end

  def find_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post, except: :index

  def index 
    @posts = current_user.has_liked
  end

  def create
    post = Post.find(params[:post_id])
    current_user.like(post)
    redirect_to post
  end

  def destroy
    post = Post.find(params[:post_id])
    current_user.unlike(post)
    redirect_to post
  end

  def find_post
    post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index] 
  before_action :find_post, only: [:show, :edit, :update]

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).order(created_at: :desc).page(params[:page]).per(10)

    respond_to do |format|
      format.html
      format.csv {send_data @posts.generate_csv, filename: "posts-#{Date.today}.csv"}
    end
  end

  def show
    counter(@post)
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create 
    @post = current_user.posts.build(post_params)
    
    if @post.save
      redirect_to root_url, notice: "#{@post.name} was successfully created"
    else
      flash.now[:danger] = 'Failed to create a post'
      render :new
    end
  end

  def update
    if @post.update!(post_params)
      redirect_to @post, notice: "#{@post.name} was successfully updated"
    else
      redirect_to @post, notice: "Failed to create a post"
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to root_url, notice: "#{post.name} was successfully deleted"
  end

  private

  def post_params
    params.require(:post).permit(:name, :price, :content, :image, :broth, :area, :shop)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @ranking = Like.ranking
    @posts = Post.find(@ranking.keys)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user
  
  def show
    @posts = Post.where(user_id: @user.id)
  end

  def likes
    @posts = @user.has_liked
  end

  private

  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
require 'navigation_helper.rb'

module ApplicationHelper
  include NavigationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/navigation_helper.rb
module NavigationHelper
  def collapsible_links_partial_path
    if user_signed_in?
      'layouts/navigation/collapsible_elements/signed_in_links'
    else
      'layouts/navigation/collapsible_elements/non_signed_in_links'
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rankings_helper.rb
module RankingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_cardbox_base.html.erb
<p>Shop: <%= post.shop %></p>
<p>Name: <%= post.name %></p>
<p>Broth: <%= post.broth %></p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <div class="container-fluid">
    
  <%= render 'layouts/navigation/header' %>

  <%= render 'layouts/navigation/collapsible_elements' %>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Raamengram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    "https://use.fontawesome.com/releases/v5.7.2/css/all.css" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/navbar' %>  
      <% if flash.notice.present? %>
        <div class="alert alert-success">
          <%= flash.notice %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/navigation/_collapsible_elements.html.erb
<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">
    <li>
      <%= link_to likes_path, class:"nav-link" do %><span class="icon"><i class="fas fa-thumbs-up"></i></span>Favorite<% end %>
    </li>
    <li>
      <%= link_to rankings_path, class:"nav-link" do %><span class="icon"><i class="fas fa-star"></i>Ranking</span><% end %>
    </li>
  </ul>

  <div>
   <%= render collapsible_links_partial_path %>
  </div> 
</div>

app/views/layouts/navigation/_header.html.erb
<div class="navbar-header">
  <%= link_to root_path, class: 'navbar-brand' do %><span class="icon"><i class="fas fa-home">Home</i></span><% end %>

  <button class="navbar-toggler " type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
</div>

app/views/layouts/navigation/collapsible_elements/_non_signed_in_links.html.erb
<ul class="navbar-nav ml-auto">
  <li>
    <%= link_to new_user_session_path, class:"nav-link", id:'signin' do %>
      <span class="icon"><i class="fas fa-sign-in-alt"></i></span>Sign in
    <% end %>
  </li>
  <li>
    <%= link_to new_user_registration_path, class:"nav-link" do %>
      <span class="icon"><i class="fas fa-user-plus"></i></span>Sign up
    <% end %>
  </li>
</ul>

app/views/layouts/navigation/collapsible_elements/_signed_in_links.html.erb
<ul class="navbar-nav ml-auto">
  <li>
    <%= link_to destroy_user_session_path, method: :delete, class:"nav-link", id:"logout" do %>
      <span class="icon"><i class="fas fa-sign-out-alt"></i></span>Logout
    <% end %>
  </li>
  <li>
    <%= link_to edit_user_registration_path(current_user), class:"nav-link" do %>
      <span class="icon"><i class="fas fa-user-edit"></i></span>Edit
    <% end %>
  </li>
</ul>

app/views/likes/index.html.erb
<h1><%= current_user.name %></h1>
<% if @posts.any? %>
  <div class="row">
    <% @posts.each do |post| %>
    <div class="col-md-6 col-lg-4">
      <div class="cardbox-heading">
        <div class="media m-0">
          <div class="media-body">
            <p class="m-0"><%= post.user.username %></p>
            <small class="float-right"><%= time_ago_in_words(post.created_at) %> ago</small>
          </div>
        </div>
      </div>
      <div class="cardbox-item">
        <%= image_tag post.image.variant(combine_options: {resize: '350', gravity: 'Center', crop: '350x350+0+0'}) if post.image.attached? %>
      </div>
      <div class="cardbox-base">
        <%= render 'layouts/cardbox_base', post: post %>
      </div>
    </div>
    <% end %>
  </div>
<% end %>

app/views/posts/_comment.html.erb
<% post.comments.each do |comment| %>
  <div class="cardbox-comment">
    <div>
      <h5 class="comment"><%= comment.user.name %></h5>
      <p class="comment"><%= time_ago_in_words(comment.created_at) %> ago</p>
    </div>
    
    <p><%= comment.comment %></p>
    
    <% if comment.user.id == current_user.id %>
      <%= link_to 'Delete', [@post, comment], method: :delete, data: {confirm: "Are you sure you want to delete this comment?" }, class: 'btn btn-danger float-right'  %>
      <div class="clear"></div>
    <% end %>
    
    <hr />
  </div>
<% end %>

app/views/posts/_form.html.erb
  <div class="row">
    <%= form_with model: @post, local: true do |f| %>
      <div class="form-group">
        <%= f.label :shop, 'Shop' %>
        <%= f.text_field :shop, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :area, 'Area' %>
        <%= f.text_field :area, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :price, 'Price' %>
        <%= f.number_field :price, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :broth, 'Broth' %>
        <%= f.text_field :broth, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :content, 'Description' %>
        <%= f.text_area :content, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :image, class: 'form-control' %>
      </div>

      <%= f.submit 'Post', class: 'btn btn-primary float-right' %>
    <% end %>
  </div>

  <div class="clear"></div>

app/views/posts/_like_button.html.erb
<% if current_user.has_liked?(@post) %>
  <%= form_for(current_user.likes.find_by(post_id: @post.id), html: { method: :delete }) do |f| %>
    <%= hidden_field_tag :post_id, @post.id %>
    <%= button_tag type: 'submit' do %>
      <span class="icon"><i class="fas fa-heart"></i></span>
    <% end %>
  <% end %>
<% else %>
  <%= form_for(current_user.likes.build) do |f| %>
    <%= hidden_field_tag :post_id, @post.id %>
    <%= button_tag type: 'submit' do %>
      <span class="icon"><i class="far fa-heart"></i></span>
    <% end %>
  <% end %>
<% end %>

app/views/posts/_photo.html.erb
<div class="cardbox-heading">
  <div class="media m-0">
    <div class="media-body">
      <h5 class="ml-1"><%= link_to post.user do %><%= post.user.username %><% end %></h5>
      <small class="float-right"><%= time_ago_in_words(post.created_at) %> ago</small>
    </div>
  </div>
</div>
<div class="cardbox-item">
  <%= image_tag post.thumbnail if post.image.attached? %>
</div>

app/views/posts/_profile.html.erb
<% if user_signed_in? %>
  <h5 class="card-header"><%= link_to user_path(current_user) do %><%= current_user.username %><% end %></h5>
  <div class="card-body">
    <p class="card-text"><%= current_user.description %></p>
  </div>
<% else %>
  <h5 class="card-header">Guest</h5>
  <div class="card-body">
    <p>You can find the ramen you want here!</p>
    <p class="card-text"><%= link_to 'Sign Up to use more functionalities', new_user_registration_path %></p>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="row">
  <%= form_with model: @post, local: true do |f| %>
    <div class="form-group">
      <%= f.label :name, 'Name' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :price, 'Price' %>
      <%= f.number_field :price, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :content, 'Description' %>
      <%= f.text_area :content, class: 'form-control' %>
    </div>

    <%= f.submit 'Post', class: 'btn btn-primary float-right' %>
  <% end %>
</div>

app/views/posts/index.html.erb
<div class="row">
  <div class="col-lg-4">
    <div class="card profile">
      <%= render 'profile' %>
      <% if user_signed_in? %>
        <%= link_to 'New Post', new_post_path, class: 'btn btn-primary' %>
      <% end %>
    </div>
    <br />

    <% if user_signed_in? %>
      <div>
        <p>Would you like to export CSV file?</p>
        <%= link_to 'Click here', posts_path(format: :csv) %>
      </div>
    <% end %>
  </div>
  
  <div class="col-lg-8">
    <div class="offset-lg-2">
      <div class="search-bar">
        <% if user_signed_in? %>
          <%= search_form_for @q do |f| %>
            <div class="form-inline">
              <%= f.search_field :shop_or_broth_or_area_cont, placeholder: 'Search by shop, area, or broth', size: '50' ,class: 'form-control' %>
              <%= button_tag type: 'submit' do %>
                <i class="fas fa-search" aria-hidden="true"></i>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    
    <div class="col-lg-8 offset-lg-2">
      <% @posts.each do |post| %>
        <section class="post">
          <div class="container">
            <div class="row">	
              <div class="cardbox shadow-lg  my-2">
                <%= render 'photo', post: post %>
                <div class="cardbox-base">
                  <%= render 'layouts/cardbox_base', post: post %>
                  <p class="float-right"><%= link_to post do %><span class="icon"><i class="fas fa-eye"></i></span>View more</p><% end %>
                </div>
              </div>
            </div>
          </div>
        </section>
      <% end %>
      <br />
      <%= paginate @posts %>
    </div>
    
  </div>

</div>

app/views/posts/new.html.erb
<div class="row">
  <div class="col-lg-4">
    <div class="card profile">
      <%= render 'profile' %>
    </div>
  </div>

  <div class="col-lg-8" id="new-post">
    <div class="d-flex justify-content-center">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-lg-4">
    <div class="card profile">
      <h5 class="card-header"><%= @post.shop %></h5>
      <div class="card-body">
        <p class="card-text">Area: <%= @post.area %></p>
      </div>
    </div>
    <br />
    <div>
      <%= form_with model: [@post, @comment], local: true do |f| %>
        <div class="form-group">
          <%= f.text_area :comment, placeholder: 'Leave a comment!' ,class: 'form-control' %>
        </div>
        <%= f.submit 'Submit', class: 'btn btn-success float-right' %>
      <% end %>
    </div>
  </div>

  <div class="col-lg-8 mt-2">
    <div class="col-lg-8 offset-lg-2">
      <section class="post">
        <div class="row">	
          <div class="cardbox shadow-lg bg-white">
            <%= render 'photo', post: @post %>
            <% if current_user.id == @post.user.id %>
              <div class="float-right">
                <%= link_to edit_post_path(@post) do %><span class="icon"><i class="fas fa-edit"></i></span><% end %>
                <%= link_to @post, method: :delete, data: {confirm: "Are you sure you want to delete this post?" } do %>
                  <span class="icon"><i class="fas fa-trash-alt"></i></span>
                <% end %>
              </div>
              <div class="clear"></div>
            <% end %>
            <div class="cardbox-base">
              <%= render 'like_button' %>
      
              <% if @count_likes == 0 %>
                <p class="likes">No one likes this post yet</p>
              <% else %>
                <h4 class="likes">+ <%= @count_likes %></h4>
              <% end %> 
              
              <p>Name: <%= @post.name %></p>
              <p>Price: <%= @post.price %> yen</p>
              <p>Broth: <%= @post.broth %></p>
              <p><%= @post.content %></p>     
            </div>

            <h4 id="comment-list">Comments:</h4>
            
            <div class="cardbox-base">
              <%= render 'comment', post: @post %>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
</div>

app/views/rankings/index.html.erb
<% if @posts.present? %>
  <div class="row">
    <div class="col-lg-4">
      <div class="card profile">
       <%= render 'posts/profile' %>
      </div>
    </div>
    <div class="col-lg-8 mt-2">
      <div class="col-lg-8 offset-lg-2">
        <% @posts.each_with_index do |post, index| %>
          <div class="container">
            <div class="row">	
              <div class="cardbox shadow-lg bg-white">
                <% if index == 0 %>
                  <h2 class="ranking"><%= index + 1 %>st</h2>
                <% elsif index == 1 %>
                  <h2 class="ranking"><%= index + 1 %>nd</h2>
                <% elsif index == 2 %>
                  <h2 class="ranking"><%= index + 1 %>rd</h2>
                <% else %>
                  <h2 class="ranking"><%= index + 1 %>th</h2>
                <% end %>
                <%= render 'posts/photo', post: post %>
                <div class="cardbox-base">
                  <%= render 'layouts/cardbox_base', post: post %>
                </div>       
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<p><%= @user.description %></p>
<% if @posts.any? %>
  <div class="row">
    <% @posts.each do |post| %>
      <div class="col-md-6 col-lg-4">
        <div class="cardbox-heading">
          <div class="media m-0">
            <div class="media-body">
              <p class="m-0"><%= @user.username %></p>
              <small class="float-right"><%= time_ago_in_words(post.created_at) %> ago</small>
            </div>
          </div>
        </div>
        <div class="cardbox-item">
          <%= image_tag post.image.variant(combine_options: {resize: '350', gravity: 'Center', crop: '350x350+0+0'}) if post.image.attached? %>
        </div>
        <div class="cardbox-base">
          <%= render 'layouts/cardbox_base', post: post %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>